polls/urls.py
from django.urls import path

from . import views

app_name = "polls"

urlpatterns = [
    path(
        "",
        views.index,
        name="index",
    ),
    path(
        "create/",
        views.create_poll,
        name="create_poll",
    ),
    path(
        "create/submit/",
        views.create_poll_submit,
        name="create_poll_submit",
    ),
    path(
        "<int:poll_id>/edit/",
        views.edit_poll,
        name="edit_poll",
    ),
    path(
        "<int:poll_id>/edit/submit/",
        views.edit_poll_submit,
        name="edit_poll_submit",
    ),
    path(
        "<int:poll_id>/delete/",
        views.delete_poll,
        name="delete_poll",
    ),
    path(
        "<int:poll_id>/questions/",
        views.questions,
        name="questions",
    ),
    path(
        "<int:poll_id>/questions/create/",
        views.create_question,
        name="create_question",
    ),
    path(
        "<int:poll_id>/questions/create/submit/",
        views.create_question_submit,
        name="create_question_submit",
    ),
    path(
        "<int:poll_id>/questions/create/add-choice/",
        views.create_question_add_choice,
        name="create_question_add_choice",
    ),
    path(
        "<int:poll_id>/questions/<int:question_id>/edit/",
        views.edit_question,
        name="edit_question",
    ),
    path(
        "<int:poll_id>/questions/<int:question_id>/edit/submit/",
        views.edit_question_submit,
        name="edit_question_submit",
    ),
    path(
        "<int:poll_id>/questions/<int:question_id>/edit/add-choice/",
        views.edit_question_add_choice,
        name="edit_question_add_choice",
    ),
    path(
        "<int:poll_id>/questions/<int:question_id>/delete/",
        views.delete_question,
        name="delete_question",
    ),
    path(
        "<int:poll_id>/",
        views.entry,
        name="entry",
    ),
    path(
        "<int:poll_id>/submit/",
        views.entry_submit,
        name="entry_submit",
    ),
    path(
        "<int:poll_id>/save-draft/",
        views.save_draft_entry,
        name="save_draft_entry",
    ),
    path(
        "<int:poll_id>/results/",
        views.results,
        name="results",
    ),
]

pollster/urls.py
from django.contrib import admin
from django.urls import include, path

import polls.views

urlpatterns = [
    path("", polls.views.index, name="home"),
    path("polls/", include("polls.urls")),
    path("subscriptions/", include("subscriptions.urls")),
    path("admin/", admin.site.urls),
]

polls/models.py
from typing import Self

from django.db import models
from django.utils import timezone


class PollQuerySet(models.QuerySet):
    def published(self) -> Self:
        return self.filter(pub_date__lt=timezone.now())

    def search(self, query: str) -> Self:
        return self.filter(title__icontains=query)


class Poll(models.Model):
    objects = PollQuerySet.as_manager()

    title = models.CharField()
    description = models.TextField(blank=True)
    pub_date = models.DateField("publication date")

    def __str__(self):
        return self.title


class Question(models.Model):
    text = models.CharField()
    order = models.PositiveIntegerField()
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)

    class Meta:
        ordering = ["order", "text"]

    def __str__(self):
        return self.text


class Choice(models.Model):
    text = models.CharField()
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    @property
    def vote_count(self) -> int:
        return self.answer_set.count()

    def __str__(self):
        return self.text


class Entry(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    date = models.DateTimeField()

    def __str__(self):
        return f"Entry for {self.poll} on {self.date}"


class Answer(models.Model):
    entry = models.ForeignKey(Entry, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)

    def __str__(self):
        return f"Answer for {self.entry}"

polls/forms.py
from django import forms
from . import models

from . import models


class IndexForm(forms.Form):
    SORT_ORDERS = [
        ("-pub_date", "Date: new to old"),
        ("pub_date", "Date: old to new"),
        ("title", "Title: A to Z"),
        ("-title", "Title: Z to A"),
    ]

    search = forms.CharField(required=False)
    sort_order = forms.ChoiceField(
        label="Sort", required=False, choices=SORT_ORDERS
    )


class PollForm(forms.ModelForm):
    class Meta:
        model = models.Poll
        fields = ["title", "description", "pub_date"]


class QuestionForm(forms.ModelForm):
    class Meta:
        model = models.Question
        fields = ["text", "order"]
        labels = {"text": "Question"}


EditChoiceFormSet = forms.inlineformset_factory(
    parent_model=models.Question,
    model=models.Choice,
    fields=["text"],
    extra=0,
)

CreateChoiceFormSet = forms.inlineformset_factory(
    parent_model=models.Question,
    model=models.Choice,
    fields=["text"],
    extra=2,
)

polls/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone
from django.contrib import messages

from . import forms, models, session


def index(request):
    """List all polls."""
    form = forms.IndexForm(request.GET)
    if not form.is_valid():
        form = forms.IndexForm()
    default_sort_order = forms.IndexForm.SORT_ORDERS[0][0]
    sort_order = form.cleaned_data["sort_order"] or default_sort_order
    polls = (
        models.Poll.objects.published()
        .search(form.cleaned_data["search"])
        .order_by(sort_order)
    )
    return render(request, "polls/index.html", {"polls": polls, "form": form})


def create_poll(request):
    """Show form to create a new poll."""
    context = {"form": forms.PollForm()}
    return render(request, "polls/create_poll.html", context)


def create_poll_submit(request):
    """Handle form to create a new poll."""
    form = forms.PollForm(request.POST)
    if not form.is_valid():
        return render(request, "polls/create_poll.html", {"form": form})
    poll = form.save()
    return redirect("polls:create_question", poll_id=poll.id)


def edit_poll(request, poll_id: int):
    """Show form to edit a poll."""
    poll = get_object_or_404(models.Poll, pk=poll_id)
    form = forms.PollForm(instance=poll)
    context = {"poll": poll, "form": form}
    return render(request, "polls/edit_poll.html", context)


def edit_poll_submit(request, poll_id: int):
    """Handle form to edit a poll."""
    poll = get_object_or_404(models.Poll, pk=poll_id)
    form = forms.PollForm(request.POST, instance=poll)
    if not form.is_valid():
        context = {"poll": poll, "form": form}
        return render(request, "polls/edit_poll.html", context)
    form.save()
    return redirect("polls:entry", poll_id=poll_id)


def delete_poll(request, poll_id: int):
    """Show form to edit a poll."""
    poll = get_object_or_404(models.Poll, pk=poll_id)
    poll.delete()
    return redirect("polls:index")


def questions(request, poll_id: int):
    """List all questions for a poll."""
    poll = get_object_or_404(models.Poll, pk=poll_id)
    return render(request, "polls/questions.html", {"poll": poll})


def create_question(request, poll_id: int):
    """Show form to create a question."""
    poll = get_object_or_404(models.Poll, pk=poll_id)
    form = forms.QuestionForm()
    choice_formset = forms.CreateChoiceFormSet()
    context = {"poll": poll, "form": form, "choice_formset": choice_formset}
    return render(request, "polls/create_question.html", context)


def create_question_submit(request, poll_id: int):
    """Handle form to create a question."""
    poll = get_object_or_404(models.Poll, pk=poll_id)
    form = forms.QuestionForm(request.POST)
    choice_formset = forms.CreateChoiceFormSet(request.POST)
    if not form.is_valid() or not choice_formset.is_valid():
        context = {"poll": poll, "form": form, "choice_formset": choice_formset}
        return render(request, "polls/create_question.html", context)
    question = form.save(commit=False)
    question.poll = poll
    question.save()
    choices = choice_formset.save(commit=False)
    for choice in choices:
        choice.question = question
        choice.save()
    return redirect("polls:create_question", poll_id=poll_id)


def create_question_add_choice(request, poll_id: int):
    """Add a choice to the form to create a question."""
    form_data = request.POST.copy()
    choice_count = int(form_data["choice_set-TOTAL_FORMS"])
    form_data["choice_set-TOTAL_FORMS"] = str(choice_count + 1)
    poll = get_object_or_404(models.Poll, pk=poll_id)
    form = forms.QuestionForm(request.POST)
    choice_formset = forms.CreateChoiceFormSet(form_data)
    context = {"poll": poll, "form": form, "choice_formset": choice_formset}
    return render(request, "polls/create_question.html", context)


def edit_question(request, poll_id: int, question_id: int):
    """Show form to edit a question."""
    poll = get_object_or_404(models.Poll, pk=poll_id)
    question = get_object_or_404(models.Question, pk=question_id)
    form = forms.QuestionForm(instance=question)
    choice_formset = forms.EditChoiceFormSet(instance=question)
    context = {
        "poll": poll,
        "question": question,
        "form": form,
        "choice_formset": choice_formset,
    }
    return render(request, "polls/edit_question.html", context)


def edit_question_submit(request, poll_id: int, question_id: int):
    """Handle form to edit a question."""
    poll = get_object_or_404(models.Poll, pk=poll_id)
    question = get_object_or_404(models.Question, pk=question_id)
    form = forms.QuestionForm(request.POST, instance=question)
    choice_formset = forms.EditChoiceFormSet(request.POST, instance=question)
    if not form.is_valid() or not choice_formset.is_valid():
        context = {
            "poll": poll,
            "question": question,
            "form": form,
            "choice_formset": choice_formset,
        }
        return render(request, "polls/edit_question.html", context)
    form.save()
    choice_formset.save()
    return redirect("polls:questions", poll_id=poll_id)


def edit_question_add_choice(request, poll_id: int, question_id: int):
    """Add a choice to the form to edit a question."""
    form_data = request.POST.copy()
    choice_count = int(form_data["choice_set-TOTAL_FORMS"])
    form_data["choice_set-TOTAL_FORMS"] = str(choice_count + 1)
    form = forms.QuestionForm(request.POST)
    question = get_object_or_404(models.Question, pk=question_id)
    choice_formset = forms.CreateChoiceFormSet(form_data, instance=question)
    poll = get_object_or_404(models.Poll, pk=poll_id)
    context = {
        "poll": poll,
        "question": question,
        "form": form,
        "choice_formset": choice_formset,
    }
    return render(request, "polls/edit_question.html", context)


def delete_question(request, poll_id: int, question_id: int):
    """Delete a question."""
    question = get_object_or_404(models.Question, pk=question_id)
    question.delete()
    return redirect("polls:questions", poll_id=poll_id)


def entry(request, poll_id: int):
    """Show a form to respond to a poll."""
    draft = session.DraftStore(request.session).get(poll_id)
    poll = models.Poll.objects.get(pk=poll_id)
    context = {"poll": poll, "draft": draft}
    return render(request, "polls/entry.html", context)


def entry_submit(request, poll_id: int):
    """Handle form to respond to a poll."""
    form_data = request.POST
    poll = get_object_or_404(models.Poll, pk=poll_id)
    entry = models.Entry(poll=poll, date=timezone.now())
    entry.save()
    for question in poll.question_set.all():
        # question and choice ids in form data are strings
        selected_choice_id = int(form_data[str(question.id)])
        selected_choice = models.Choice.objects.get(pk=selected_choice_id)
        answer = models.Answer(entry=entry, choice=selected_choice)
        answer.save()
    session.DraftStore(request.session).delete(poll_id)
    messages.success(request, "Your entry has been submitted.")
    return redirect("polls:results", poll_id=poll_id)


def save_draft_entry(request, poll_id: int):
    """Handle form to save a draft entry."""
    session.DraftStore(request.session).add(request.POST, poll_id)
    return redirect("polls:results", poll_id=poll_id)


def results(request, poll_id: int):
    """Show results for a poll."""
    poll = get_object_or_404(models.Poll, pk=poll_id)
    context = {"poll": poll}
    return render(request, "polls/results.html", context)

polls/templates/polls/create_poll.html
{% extends "base.html" %}
{% block title %}Create poll{% endblock %}
{% block breadcrumbs %}
    <li><a href="{% url 'polls:index' %}">Polls</a></li>
    <li><a href="{% url 'polls:create_poll' %}">Create poll</a></li>
{% endblock %}
{% block main %}
    <h1>Create a poll</h1>
    <form method="post" action="{% url 'polls:create_poll_submit' %}">
        {% csrf_token %}
        {{ form }}
        <button>Submit</button>
    </form>
{% endblock main %}

polls/templates/polls/create_question.html
{% extends "base.html" %}
{% block title %}Add question | {{ poll.title }}{% endblock %}
{% block breadcrumbs %}
    <li><a href="{% url 'polls:index' %}">Polls</a></li>
    <li><a href="{% url 'polls:entry' poll.id %}">{{ poll.title }}</a></li>
    <li><a href="{% url 'polls:questions' poll.id %}">Questions</a></li>
    <li>
        <a href="{% url 'polls:create_question' poll.id %}">Add question</a>
    </li>
{% endblock %}
{% block main %}
    <h1>{{ poll.title }}<span>Add question</span></h1>
    <form
        method="post"
        action="{% url 'polls:create_question_submit' poll.id %}"
    >
        {% csrf_token %}
        {{ form }}
        {{ choice_formset }}
        <button
            formaction="{% url 'polls:create_question_add_choice' poll.id %}"
            formnovalidate
        >
            Add choice
        </button>
        <button>Save</button>
    </form>
{% endblock main %}

polls/templates/polls/edit_poll.html
{% extends "base.html" %}
{% block title %}Edit poll | {{ poll.title }}{% endblock %}
{% block breadcrumbs %}
    <li><a href="{% url 'polls:index' %}">Polls</a></li>
    <li><a href="{% url 'polls:entry' poll.id %}">{{ poll.title }}</a></li>
    <li><a href="{% url 'polls:edit_poll' poll.id %}">Edit poll</a></li>
{% endblock %}
{% block main_nav %}
    <li><a href="{% url 'polls:questions' poll.id %}">Questions</a></li>
{% endblock %}
{% block main %}
    <h1>{{ poll.title }}<span>Edit poll</span></h1>
    <form method="post" action="{% url 'polls:edit_poll_submit' poll.id %}">
        {% csrf_token %}
        {{ form }}
        <button>Save</button>
    </form>
{% endblock main %}

polls/templates/polls/edit_question.html
{% extends "base.html" %}
{% block title %}Edit question | {{ poll.title }}{% endblock %}
{% block breadcrumbs %}
    <li><a href="{% url 'polls:index' %}">Polls</a></li>
    <li><a href="{% url 'polls:entry' poll.id %}">{{ poll.title }}</a></li>
    <li><a href="{% url 'polls:questions' poll.id %}">Questions</a></li>
    <li>
        <a href="{% url 'polls:edit_question' poll.id question.id %}">Edit</a>
    </li>
{% endblock %}
{% block main %}
    <h1>{{ poll.title }}<span>Edit question</span></h1>
    <form
        method="post"
        action="{% url 'polls:edit_question_submit' poll.id question.id %}"
    >
        {% csrf_token %}
        {{ form }}
        {{ choice_formset }}
        <button
            formaction="{% url 'polls:edit_question_add_choice' poll.id question.id %}"
            formnovalidate
        >
            Add choice
        </button>
        <button>Save</button>
    </form>
{% endblock main %}

polls/templates/polls/entry.html
{% extends "base.html" %}
{% load poll_extras %}
{% block title %}{{ poll }}{% endblock %}
{% block breadcrumbs %}
    <li><a href="{% url 'polls:index' %}">Polls</a></li>
    <li><a href="{% url 'polls:entry' poll.id %}">{{ poll.title }}</a></li>
{% endblock %}
{% block main_nav %}
    <li><a href="{% url 'polls:results' poll.id %}">Results</a></li>
    <li><a href="{% url 'polls:edit_poll' poll.id %}">Edit</a></li>
    <li><a href="{% url 'polls:delete_poll' poll.id %}">Delete</a></li>
{% endblock %}
{% block main %}
    <h1>{{ poll }}<span>Answer poll</span></h1>
    <form
        method="post"
        action="{% url 'polls:entry_submit' poll.id %}"
        class="entry"
    >
        {% csrf_token %}
        {% for question in poll.question_set.all %}
            <div>
                <fieldset>
                    <legend class="question">{{ question.text }}</legend>
                    {% for choice in question.choice_set.all %}
                        <label class="choice">
                            <input
                                type="radio"
                                name="{{ question.id }}"
                                value="{{ choice.id }}"
                                required
                                {% if draft|get:question.id == choice.id %}
                                    checked
                                {% endif %}
                            />
                            <span>{{ choice.text }}</span>
                        </label>
                    {% endfor %}
                </fieldset>
            </div>
        {% endfor %}
        <button>Submit</button>
        <button
            formnovalidate
            formaction="{% url 'polls:save_draft_entry' poll.id %}"
        >
            Save draft
        </button>
    </form>
{% endblock main %}

polls/templates/polls/index.html
{% extends "base.html" %}
{% block title %}Polls{% endblock %}
{% block breadcrumbs %}
    <li><a href="{% url 'home' %}">Home</a></li>
{% endblock %}
{% block main %}
    <h1>Polls</h1>
    <form id="index-form">
        {{ form }} <button>Apply</button>
    </form>
    <ul>
        {% for poll in polls %}
            <li>
                <a href="{% url 'polls:entry' poll.id %}">
                    {{ poll.title }}
                </a>
            </li>
        {% endfor %}
    </ul>
{% endblock main %}

polls/templates/polls/questions.html
{% extends "base.html" %}
{% block title %}Questions | {{ poll.title }}{% endblock %}
{% block breadcrumbs %}
    <li><a href="{% url 'polls:index' %}">Polls</a></li>
    <li><a href="{% url 'polls:entry' poll.id %}">{{ poll.title }}</a></li>
    <li><a href="{% url 'polls:questions' poll.id %}">Questions</a></li>
{% endblock %}
{% block main %}
    <h1>{{ poll.title }}<span>Questions</span></h1>
    <ul>
        {% for question in poll.question_set.all %}
            <li>
                {{ question.text }}
                <form
                    method="post"
                    action="{% url 'polls:edit_question' poll.id question.id %}"
                >
                    {% csrf_token %}
                    <button>Edit</button>
                </form>
                <form
                    method="post"
                    action="{% url 'polls:delete_question' poll.id question.id %}"
                >
                    {% csrf_token %}
                    <button>Delete</button>
                </form>
            </li>
        {% endfor %}
    </ul>
    <a href="{% url 'polls:create_question' poll.id %}">Add question</a>
{% endblock main %}

polls/templates/polls/results.html
{% extends "base.html" %}
{% block title %}Results: {{ poll }}{% endblock %}
{% block breadcrumbs %}
    <li><a href="{% url 'polls:index' %}">Polls</a></li>
    <li><a href="{% url 'polls:entry' poll.id %}">{{ poll.title }}</a></li>
    <li><a href="{% url 'polls:results' poll.id %}">Results</a></li>
{% endblock %}
{% block main %}
    <h1>{{ poll }}<span>Results</span></h1>
    <ul class="entry">
        {% for question in poll.question_set.all %}
            <li class="question">
                {{ question.text }}
                <ul class="choice-list">
                    {% for choice in question.choice_set.all %}
                        <li>
                            <span class="votes">{{ choice.vote_count }}</span>
                            <span>{{ choice.text }}</span>
                        </li>
                    {% endfor %}
                </ul>
            </li>
        {% endfor %}
    </ul>
{% endblock main %}